Move unpacking eggs bundle to portia-entrypoint
scrapinghub/scrapinghub-stack-portia pull request #28
Opened 2017-02-20 08:34 UTC by vshlapakov

WIP.

2017-02-27 10:11 UTC, vshlapakov commented on portia-entrypoint
> +        if cmd == 'start-crawl':
Please, note, that I dropped logic for `scrapy-list` here, looks like it's useless as for now we don't use portia-stack with builder.

2017-02-27 11:44 UTC, chekunkov requested changes

2017-02-27 11:44 UTC, chekunkov commented on portia-entrypoint
> +        pypath += '%s:' % egg_path
if pypath is not empty and doesn't end with colon you'll get a malformed pythonpath here. also I think u may want dash eggs to be at the beginning of the path, not appended to the end

2017-02-27 11:44 UTC, chekunkov commented on portia-entrypoint
> +    # os.remove(eggpath)
hm, why we don't have permission to remove from tmp?

2017-02-27 14:16 UTC, vshlapakov commented on portia-entrypoint
> +    # os.remove(eggpath)
Right as now we unpack eggs bundle to tmp 👍

2017-02-27 14:46 UTC, vshlapakov commented on portia-entrypoint
> +    eggs_environment = load_dash_eggs([DASH_PACKED_EGGS_PATH,
We also have to load addons eggs built-in to the stack, the only question is whether we should allow to replace the addons eggs with custom eggs or not (it's defined by precedence of the paths here). Assuming that we're moving away from eggs completely, I think it's fine to keep it as-is, but let me know if you disagree

2017-02-27 16:32 UTC, chekunkov commented on portia-entrypoint
> +        # on PYTHONPATH already for "scrapy list".
is this note about "scrapy list" still relevant?

2017-03-03 10:28 UTC, vshlapakov commented
@chekunkov Let me know if there's anything else awaiting for me, looks like everything is covered

2017-03-06 12:42 UTC, chekunkov approved these changes

2017-03-06 12:45 UTC, chekunkov commented
@vshlapakov lgtm, do we need to wait for the new entrypoint to be released before we merge this pr, or this one is still compatible with current one?

2017-03-07 08:02 UTC, vshlapakov commented
@chekunkov Have just checked it in a case, the PR is compatible with current entrypoint, the only drawback I should mention about is that some work is done twice, for now eggs bundle is:
- downloaded with Mesos to sandbox dir & unpacked with kumo-entrypoint to /app
- downloaded with portia-entrypoint to /tmp/ & unpacked to /tmp/unpacked-eggs

But it looks like a necessary transition state, when portia-stack is updated we're able to:
- stop providing eggs bundle with Mesos
- replace kumo-entrypoint with new version when it's ready

2017-03-07 12:18 UTC, chekunkov commented
In this case we can merge and try it out on prod

2017-03-07 13:54 UTC, merged